### ISSUE TITLE
When using on a text field inputView

### ISSUE THREAD

**Issue by markst** [ActionKit/ActionKit#27]
I use action kit on a `UIDatePicker` as follows:

```swift
fileprivate func setupDatePicker(on textField: UITextField, mode: UIDatePickerMode = .date) {
    let datePicker = UIDatePicker()
    datePicker.date = Date()
    datePicker.datePickerMode = mode
    datePicker.setValue(UIColor.cs_CongressBlue(), forKeyPath: "textColor")
    datePicker.backgroundColor = UIColor(red: 245/255, green: 245/255, blue: 245/255, alpha: 1.0)
    datePicker.addControlEvent(.valueChanged) { [unowned datePicker, unowned self] in
        if mode == .countDownTimer {
            textField.text = "\(Int(datePicker.countDownDuration/60)) Minutes"
        } else {
            textField.text = self.dateFormatter.string(from: datePicker.date)
        }
    }
    
    textField.inputView = datePicker
}
```

The way Apple handles input views if they are removed when changing to another input view. 
This result in calling `removeFromSuperview()` and in turn `clearActionKit()`. Which means the next time the input view is presented - there no actions.

**Comment by coolbnjmn** [comment]
Hmm, I see the issue there. `removeFromSuperview()` sounds like it's not the right trigger for `clearActionKit()` in your situation, but only `deinit` would call `clearActionKit()` properly for you it seems, yet in an extension it's not possible to override/add a `deinit` method, so that's not an option for *ActionKit* the way I see it right now.

There should be a workable workaround though, that may make sense to bundle into the library if possible. From what you're showing me, this datePicker that is being initialized in the `setupDatePicker` method leaves the `textField` to keep the reference in it's `inputView`. You're then also saying that this view reference is kept but added/removed several times during the `textField`s lifecycle, which calls `clearActionKit()` on each `removeFromSuperview()`, right? Hoping that I understood the problem correctly, a workaround you could try is:
  - in the class setting up the date picker, AKA the textField, add a reference to the control event's closure. In your case, it looks like something of this form would work: 
`(I am assuming [unowned self] is referencing a UITextField, but replace this with whatever class is creating the datePicker)`
```
var datePickerControlEvent: ((UIDatePicker picker, UITextField textField)->()) =  { [unowned datePicker, unowned self] in
        if mode == .countDownTimer {
            textField.text = "\(Int(datePicker.countDownDuration/60)) Minutes"
        } else {
            textField.text = self.dateFormatter.string(from: datePicker.date)
        }
    }
``` 
and then in the setupDatePicker method, you'd simply:
```
    datePicker.addControlEvent(.valueChanged, datePickerControlEvent)
```
and you can then do the following in the lifecycle method to continually re-add it as necessary in 1-line:
```
(textField.inputView as? UIDatePicker)?.addControlEvent(.valueChanged, datePickerControlEvent)
```
optional casting above simply to show what view that is, but you'd probably not need it to have this compile. That line can then be put in your `viewDidLoad`, or `viewDidAppear`, or whatever other lifecycle method you might need to add it in. If this, when implemented, seems like something that makes sense to put into the library, I'm more than happy to accept a PR :)

Thank you for reporting this issue, I am sorry for the 9 day delay after a big update (I just got back from a vacation, first in a while, phew). Anyways, I'm back at it, and I really wanted to thank you for this bug report. I hope I've answered you're question, but if not please let me know if ^^ solutions do not work for you. 

Thanks,
- Benjamin

**Comment by coolbnjmn** [comment]
I'm going to close this, as I believe that I have provided an adequate solution to your issue. I hope I did, but if I didn't, please feel free to re open or create a new issue @markst or anyone else looking at this.
