### ISSUE TITLE
Swift 4

### ISSUE THREAD

**Issue by Gerst20051** [ActionKit/ActionKit#29]
Any updates on the progress to update this for Swift 4?

`ActionKit.swift:118:30: Instance method 'append' expects a single parameter of type '(String, ActionKitClosure)'`

`gestureArr.append(name, closure)` should be `gestureArr.append((name, closure))`

**Comment by coolbnjmn** [comment]
I'm not sure about the second part of your issue.

As far as Swift 4, I'm happy to accept a PR to support Swift 4, but since Xcode9 fully supports Swift 3, I don't see a need for it right away.

**Comment by coolbnjmn** [comment]
Turns out @brandons opened a PR, and I happily just merged it for ActionKit version 2.1 

Swift 3.2 branch incoming, for backwards compatibility should that be desired. I hope this answers your issue, and I will be closing this now, please feel free to open another one if you have any issues!

Thanks again for reporting this @Gerst20051
